# Generated by Django 2.0.6 on 2018-06-26 20:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='Coin Sahibi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Neden')),
                ('quantity', models.CharField(max_length=10, verbose_name='Miktar')),
            ],
        ),
    ]
