# Generated by Django 2.0.6 on 2018-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180630_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='quantity',
            field=models.IntegerField(verbose_name='Miktar'),
        ),
    ]
