# Generated by Django 2.0.6 on 2018-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180623_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya Ekle'),
        ),
    ]
