# Generated by Django 2.0.6 on 2018-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_article_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_file',
        ),
        migrations.AddField(
            model_name='article',
            name='finished_date',
            field=models.CharField(default='', max_length=10, verbose_name='Bitirilmesi Gereken Tarih'),
        ),
    ]
